// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVfxY0USp5W80gp4D-AqlIdQTSXKiIXa8',
    appId: '1:318958996195:web:c4ddedf069ae5a312293d6',
    messagingSenderId: '318958996195',
    projectId: 'laruina-rmmonki',
    authDomain: 'laruina-rmmonki.firebaseapp.com',
    storageBucket: 'laruina-rmmonki.appspot.com',
    measurementId: 'G-BF8SLK304Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3OFKGZu5Ufv7zJbPPdedHtN6ebFysFWU',
    appId: '1:318958996195:android:11e03284a182385e2293d6',
    messagingSenderId: '318958996195',
    projectId: 'laruina-rmmonki',
    storageBucket: 'laruina-rmmonki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqBUM-61f7KELIMo4ntF5EvDjJe5Lr-tg',
    appId: '1:318958996195:ios:c8640a33596b2aa62293d6',
    messagingSenderId: '318958996195',
    projectId: 'laruina-rmmonki',
    storageBucket: 'laruina-rmmonki.appspot.com',
    androidClientId: '318958996195-stlus058jia04bkli3idrv73d3sb1nlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.laruina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqBUM-61f7KELIMo4ntF5EvDjJe5Lr-tg',
    appId: '1:318958996195:ios:c8640a33596b2aa62293d6',
    messagingSenderId: '318958996195',
    projectId: 'laruina-rmmonki',
    storageBucket: 'laruina-rmmonki.appspot.com',
    androidClientId: '318958996195-stlus058jia04bkli3idrv73d3sb1nlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.laruina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVfxY0USp5W80gp4D-AqlIdQTSXKiIXa8',
    appId: '1:318958996195:web:ba91d7b6fef88e2a2293d6',
    messagingSenderId: '318958996195',
    projectId: 'laruina-rmmonki',
    authDomain: 'laruina-rmmonki.firebaseapp.com',
    storageBucket: 'laruina-rmmonki.appspot.com',
    measurementId: 'G-2S13LEVJMQ',
  );

}